ast.o: ast.c ast.h
functions.o: functions.c functions.h string.h
interpret.o: interpret.c
main.o: main.c common.h string.h parser.h gc.h
parser.o: parser.c common.h string.h parser.h scanner.h interpret.h gc.h
scanner.o: scanner.c common.h string.h
stack.o: stack.c stack.h string.h gc.h
string.o: string.c string.h gc.h
